// Generated by gencpp from file srv_test/test.msg
// DO NOT EDIT!


#ifndef SRV_TEST_MESSAGE_TEST_H
#define SRV_TEST_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <srv_test/testRequest.h>
#include <srv_test/testResponse.h>


namespace srv_test
{

struct test
{

typedef testRequest Request;
typedef testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test
} // namespace srv_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_test::test > {
  static const char* value()
  {
    return "fd72814fc41c6bccdf8759d8dea09f77";
  }

  static const char* value(const ::srv_test::test&) { return value(); }
};

template<>
struct DataType< ::srv_test::test > {
  static const char* value()
  {
    return "srv_test/test";
  }

  static const char* value(const ::srv_test::test&) { return value(); }
};


// service_traits::MD5Sum< ::srv_test::testRequest> should match 
// service_traits::MD5Sum< ::srv_test::test > 
template<>
struct MD5Sum< ::srv_test::testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_test::test >::value();
  }
  static const char* value(const ::srv_test::testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_test::testRequest> should match 
// service_traits::DataType< ::srv_test::test > 
template<>
struct DataType< ::srv_test::testRequest>
{
  static const char* value()
  {
    return DataType< ::srv_test::test >::value();
  }
  static const char* value(const ::srv_test::testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_test::testResponse> should match 
// service_traits::MD5Sum< ::srv_test::test > 
template<>
struct MD5Sum< ::srv_test::testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_test::test >::value();
  }
  static const char* value(const ::srv_test::testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_test::testResponse> should match 
// service_traits::DataType< ::srv_test::test > 
template<>
struct DataType< ::srv_test::testResponse>
{
  static const char* value()
  {
    return DataType< ::srv_test::test >::value();
  }
  static const char* value(const ::srv_test::testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_TEST_MESSAGE_TEST_H
