// Generated by gencpp from file wizavo/wizavo.msg
// DO NOT EDIT!


#ifndef WIZAVO_MESSAGE_WIZAVO_H
#define WIZAVO_MESSAGE_WIZAVO_H

#include <ros/service_traits.h>


#include <wizavo/wizavoRequest.h>
#include <wizavo/wizavoResponse.h>


namespace wizavo
{

struct wizavo
{

typedef wizavoRequest Request;
typedef wizavoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct wizavo
} // namespace wizavo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wizavo::wizavo > {
  static const char* value()
  {
    return "fd72814fc41c6bccdf8759d8dea09f77";
  }

  static const char* value(const ::wizavo::wizavo&) { return value(); }
};

template<>
struct DataType< ::wizavo::wizavo > {
  static const char* value()
  {
    return "wizavo/wizavo";
  }

  static const char* value(const ::wizavo::wizavo&) { return value(); }
};


// service_traits::MD5Sum< ::wizavo::wizavoRequest> should match 
// service_traits::MD5Sum< ::wizavo::wizavo > 
template<>
struct MD5Sum< ::wizavo::wizavoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wizavo::wizavo >::value();
  }
  static const char* value(const ::wizavo::wizavoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wizavo::wizavoRequest> should match 
// service_traits::DataType< ::wizavo::wizavo > 
template<>
struct DataType< ::wizavo::wizavoRequest>
{
  static const char* value()
  {
    return DataType< ::wizavo::wizavo >::value();
  }
  static const char* value(const ::wizavo::wizavoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wizavo::wizavoResponse> should match 
// service_traits::MD5Sum< ::wizavo::wizavo > 
template<>
struct MD5Sum< ::wizavo::wizavoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wizavo::wizavo >::value();
  }
  static const char* value(const ::wizavo::wizavoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wizavo::wizavoResponse> should match 
// service_traits::DataType< ::wizavo::wizavo > 
template<>
struct DataType< ::wizavo::wizavoResponse>
{
  static const char* value()
  {
    return DataType< ::wizavo::wizavo >::value();
  }
  static const char* value(const ::wizavo::wizavoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WIZAVO_MESSAGE_WIZAVO_H
