// Generated by gencpp from file my_dynamixel_tutorial/servo_service.msg
// DO NOT EDIT!


#ifndef MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICE_H
#define MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICE_H

#include <ros/service_traits.h>


#include <my_dynamixel_tutorial/servo_serviceRequest.h>
#include <my_dynamixel_tutorial/servo_serviceResponse.h>


namespace my_dynamixel_tutorial
{

struct servo_service
{

typedef servo_serviceRequest Request;
typedef servo_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct servo_service
} // namespace my_dynamixel_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_dynamixel_tutorial::servo_service > {
  static const char* value()
  {
    return "4641bb0523a3557209606d9bd91ce33a";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_service&) { return value(); }
};

template<>
struct DataType< ::my_dynamixel_tutorial::servo_service > {
  static const char* value()
  {
    return "my_dynamixel_tutorial/servo_service";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_service&) { return value(); }
};


// service_traits::MD5Sum< ::my_dynamixel_tutorial::servo_serviceRequest> should match 
// service_traits::MD5Sum< ::my_dynamixel_tutorial::servo_service > 
template<>
struct MD5Sum< ::my_dynamixel_tutorial::servo_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_dynamixel_tutorial::servo_service >::value();
  }
  static const char* value(const ::my_dynamixel_tutorial::servo_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_dynamixel_tutorial::servo_serviceRequest> should match 
// service_traits::DataType< ::my_dynamixel_tutorial::servo_service > 
template<>
struct DataType< ::my_dynamixel_tutorial::servo_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::my_dynamixel_tutorial::servo_service >::value();
  }
  static const char* value(const ::my_dynamixel_tutorial::servo_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_dynamixel_tutorial::servo_serviceResponse> should match 
// service_traits::MD5Sum< ::my_dynamixel_tutorial::servo_service > 
template<>
struct MD5Sum< ::my_dynamixel_tutorial::servo_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_dynamixel_tutorial::servo_service >::value();
  }
  static const char* value(const ::my_dynamixel_tutorial::servo_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_dynamixel_tutorial::servo_serviceResponse> should match 
// service_traits::DataType< ::my_dynamixel_tutorial::servo_service > 
template<>
struct DataType< ::my_dynamixel_tutorial::servo_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::my_dynamixel_tutorial::servo_service >::value();
  }
  static const char* value(const ::my_dynamixel_tutorial::servo_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICE_H
