// Generated by gencpp from file my_dynamixel_tutorial/servo_rad.msg
// DO NOT EDIT!


#ifndef MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_RAD_H
#define MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_RAD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_dynamixel_tutorial
{
template <class ContainerAllocator>
struct servo_rad_
{
  typedef servo_rad_<ContainerAllocator> Type;

  servo_rad_()
    : id(0)
    , rad(0.0)  {
    }
  servo_rad_(const ContainerAllocator& _alloc)
    : id(0)
    , rad(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _id_type;
  _id_type id;

   typedef double _rad_type;
  _rad_type rad;





  typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> const> ConstPtr;

}; // struct servo_rad_

typedef ::my_dynamixel_tutorial::servo_rad_<std::allocator<void> > servo_rad;

typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_rad > servo_radPtr;
typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_rad const> servo_radConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_dynamixel_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_dynamixel_tutorial': ['/home/icd/catkin_ws/src/my_dynamixel_tutorial/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fcd47675421d9290eb38e0a90977cd6";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fcd47675421d929ULL;
  static const uint64_t static_value2 = 0x0eb38e0a90977cd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_dynamixel_tutorial/servo_rad";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 id\n\
float64 rad\n\
";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_rad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_dynamixel_tutorial::servo_rad_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "rad: ";
    Printer<double>::stream(s, indent + "  ", v.rad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_RAD_H
