// Generated by gencpp from file my_dynamixel_tutorial/servo_serviceRequest.msg
// DO NOT EDIT!


#ifndef MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICEREQUEST_H
#define MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_dynamixel_tutorial
{
template <class ContainerAllocator>
struct servo_serviceRequest_
{
  typedef servo_serviceRequest_<ContainerAllocator> Type;

  servo_serviceRequest_()
    : speed(0.0)  {
    }
  servo_serviceRequest_(const ContainerAllocator& _alloc)
    : speed(0.0)  {
  (void)_alloc;
    }



   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct servo_serviceRequest_

typedef ::my_dynamixel_tutorial::servo_serviceRequest_<std::allocator<void> > servo_serviceRequest;

typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_serviceRequest > servo_serviceRequestPtr;
typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_serviceRequest const> servo_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_dynamixel_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_dynamixel_tutorial': ['/home/icd/catkin_ws/src/my_dynamixel_tutorial/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4641bb0523a3557209606d9bd91ce33a";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4641bb0523a35572ULL;
  static const uint64_t static_value2 = 0x09606d9bd91ce33aULL;
};

template<class ContainerAllocator>
struct DataType< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_dynamixel_tutorial/servo_serviceRequest";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 speed\n\
\n\
";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_dynamixel_tutorial::servo_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICEREQUEST_H
