// Generated by gencpp from file my_dynamixel_tutorial/servo_serviceResponse.msg
// DO NOT EDIT!


#ifndef MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICERESPONSE_H
#define MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_dynamixel_tutorial
{
template <class ContainerAllocator>
struct servo_serviceResponse_
{
  typedef servo_serviceResponse_<ContainerAllocator> Type;

  servo_serviceResponse_()
    {
    }
  servo_serviceResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct servo_serviceResponse_

typedef ::my_dynamixel_tutorial::servo_serviceResponse_<std::allocator<void> > servo_serviceResponse;

typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_serviceResponse > servo_serviceResponsePtr;
typedef boost::shared_ptr< ::my_dynamixel_tutorial::servo_serviceResponse const> servo_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_dynamixel_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_dynamixel_tutorial': ['/home/icd/catkin_ws/src/my_dynamixel_tutorial/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_dynamixel_tutorial/servo_serviceResponse";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::my_dynamixel_tutorial::servo_serviceResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MY_DYNAMIXEL_TUTORIAL_MESSAGE_SERVO_SERVICERESPONSE_H
